/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

double *add_1_svc(mypair *argp, struct svc_req *rqstp) {
	static double  result = 0;
	double a = argp->arg1;
	double b = argp->arg2;
	result = a + b;
	LOG("%lf + %lf = %lf\n", a, b, result);
	return &result;
}

double *subtract_1_svc(mypair *argp, struct svc_req *rqstp) {
	static double  result = 0;
	double a = argp->arg1;
	double b = argp->arg2;
	result = a - b;
	LOG("%lf - %lf = %lf\n", a, b, result);
	return &result;
}

double *multiple_1_svc(mypair *argp, struct svc_req *rqstp)
{
	static double  result = 0;
	double a = argp->arg1;
	double b = argp->arg2;
	result = a * b;
	LOG("%lf * %lf = %lf\n", a, b, result);
	return &result;
}

double *divide_1_svc(mypair *argp, struct svc_req *rqstp)
{
	static double  result = 0;
	double a = argp->arg1;
	double b = argp->arg2;
	if (b == 0) {
		LOG("divide by zero error\n");
		return NULL;
	} else {
		result = a / b;
		LOG("%lf / %lf = %lf\n", a, b, result);
	}
	return &result;
}
