/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/stat.h>
#include <arpa/inet.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
mcprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		mypair add_1_arg;
		mypair subtract_1_arg;
		mypair multiple_1_arg;
		mypair divide_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ADD:
		_xdr_argument = (xdrproc_t) xdr_mypair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) add_1_svc;
		break;

	case SUBTRACT:
		_xdr_argument = (xdrproc_t) xdr_mypair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) subtract_1_svc;
		break;

	case MULTIPLE:
		_xdr_argument = (xdrproc_t) xdr_mypair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) multiple_1_svc;
		break;

	case DIVIDE:
		_xdr_argument = (xdrproc_t) xdr_mypair;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) divide_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		LOG("%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void check_pid(pid_t pid) {
	if (pid < 0)
		exit(EXIT_FAILURE);
	if (pid > 0) {
		FILE *fp;
		fp = fopen("/var/run/calc_server.pid", "w");
		if (!fp) {
			perror("fopen");
			exit(EXIT_FAILURE);
		}
		fprintf(fp, "%d\n", pid);
		fclose(fp);
		exit(EXIT_SUCCESS);
	}
}

void skeleton_daemon(void) {
	int fd;
	pid_t pid;

	pid = fork();
	check_pid(pid);
	if (setsid() < 0)
		exit(EXIT_FAILURE);

	pid = fork();
	check_pid(pid);

	umask(0);
	chdir("/");
	for (fd = sysconf(_SC_OPEN_MAX); fd > 0; fd--)
		close(fd);
	openlog("c_daemon", LOG_PID, LOG_DAEMON);
}


int main (void)
{
	register SVCXPRT *transp;
#ifdef DAEMONIZE
	skeleton_daemon();
#endif
	pmap_unset (MCPROG, MCVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		LOG("%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MCPROG, MCVERS, mcprog_1, IPPROTO_UDP)) {
		LOG("%s", "unable to register (MCPROG, MCVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		LOG("%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MCPROG, MCVERS, mcprog_1, IPPROTO_TCP)) {
		LOG("%s", "unable to register (MCPROG, MCVERS, tcp).");
		exit(1);
	}

	svc_run();
	LOG("%s", "svc_run returned");
	closelog();
	exit (1);
	/* NOTREACHED */
}
